/*
 * File: app/view/AddingProductsToHamperWin.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AddingProductsToHamperWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.addingproductstohamperwin',

    requires: [
        'cobuy.view.AddingProductsToHamperForm',
        'Ext.form.Panel'
    ],

    height: 650,
    id: 'addingproductstohamperwin',
    width: 1200,
    layout: 'fit',
    title: 'Add or Remove Items from Hamper & Gift Container',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'addingproductstohamperform'
                }
            ]
        });

        me.callParent(arguments);
    }

});