/*
 * File: app/view/AddingProductsToHamperForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AddingProductsToHamperForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addingproductstohamperform',

    requires: [
        'cobuy.view.SearchProductForHamperForm',
        'Ext.form.FieldSet',
        'Ext.form.Panel',
        'Ext.view.View',
        'Ext.XTemplate',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill'
    ],

    height: 531,
    width: 800,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 3,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Hamper Label',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Hamper Label',
                                    name: 'hamper_label',
                                    readOnly: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 8.5,
                    margin: 3,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1.5,
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 6,
                                    itemId: 'productContainer',
                                    margin: 3,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Products',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    margin: 5,
                                                    layout: 'anchor',
                                                    items: [
                                                        {
                                                            xtype: 'searchproductforhamperform'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 7,
                                                    autoScroll: true,
                                                    layout: 'fit',
                                                    items: [
                                                        {
                                                            xtype: 'dataview',
                                                            prepareData: function(data) {
                                                                var price = data.prevailing_retail_selling_price;

                                                                Ext.apply(data, {
                                                                    shortDesc: Ext.util.Format.ellipsis("_______________", 15),
                                                                    shortName: Ext.util.Format.ellipsis(data.name, 15),
                                                                    price: Ext.util.Format.currency(price,'=N=',2)
                                                                    //min_subs_no: Ext.util.Format.number(data.min_subscription_required, '0,000,000'),
                                                                    //visibility: Ext.util.Format.ellipsis(data.visibility, 15),
                                                                    //location: Ext.util.Format.ellipsis(data.storage_location, 15)
                                                                });


                                                                return data;

                                                            },
                                                            cls: 'my-dataview-cls',
                                                            itemId: 'productDataview',
                                                            margin: 5,
                                                            overflowY: 'auto',
                                                            itemSelector: 'div.thumb-wrap',
                                                            itemTpl: [
                                                                '<tpl for=".">',
                                                                '    <div style="float:left;padding:	10px 30px 30px 18px;  "class=thumb-wrap id="id">',
                                                                '        <div class=thumb><img src="../cobuy_images/icons/{icon}"  height="90" width="50"></div>',
                                                                '        <div>',
                                                                '        <h5> <b>{shortName} </b></br></h5>',
                                                                '        <h5><em>{price} </em></br></h5>',
                                                                '        <h5> <b>{shortDesc} </b></br></h5>',
                                                                '            ',
                                                                '        <!--<spam>{description} </spam> -->',
                                                                '        <!--  <span style=class=x-editable>{shortDesc}</span>-->',
                                                                '        <!--<span style="padding-right:5px">price/user/yr:</span><span style=class=x-editable>{price}</span>-->',
                                                                '        <!--<span style="padding-right:5px">visibility:</span><span style=class=x-editable>{visibility}</span>',
                                                                '        <!--<span style="padding-right:5px">location:</span><span style=class=x-editable>{location}</span>-->',
                                                                '        <!--<br>min subscription no.:<span style="padding-left:5px">{min_subs_no}</span></br>-->',
                                                                '        </div>',
                                                                '        ',
                                                                '    </tpl>',
                                                                '<div class=x-clear></div>'
                                                            ],
                                                            preserveScrollOnRefresh: true,
                                                            store: 'ProductsThatCouldBeInHamper'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 3,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            margin: 5,
                                            title: 'Add Product to Hamper ',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 7,
                                                            itemId: 'productName',
                                                            fieldLabel: 'Product',
                                                            name: 'add_product_name',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'numberfield',
                                                            flex: 1,
                                                            itemId: 'quantityName',
                                                            margin: '0 0 0 3',
                                                            name: 'product_quantity',
                                                            value: 1,
                                                            minValue: 1
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            itemId: 'addhamperBtn',
                                                            margin: '0 0 0 3',
                                                            iconCls: 'add',
                                                            text: 'Add'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            itemId: 'hamperContainer',
                            margin: 10,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 5,
                                    margin: 3,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            layout: 'fit',
                                            title: 'Products in the Hamper & Gift Container',
                                            items: [
                                                {
                                                    xtype: 'dataview',
                                                    prepareData: function(data) {
                                                        var price = data.prevailing_retail_selling_price;

                                                        console.log('tis data is:',data);

                                                        Ext.apply(data, {
                                                            shortDesc: Ext.util.Format.ellipsis("_______________", 15),
                                                            shortName: Ext.util.Format.ellipsis(data.name, 15),
                                                            price: Ext.util.Format.currency(price,'=N=',2)
                                                            //min_subs_no: Ext.util.Format.number(data.min_subscription_required, '0,000,000'),
                                                            //visibility: Ext.util.Format.ellipsis(data.visibility, 15),
                                                            //location: Ext.util.Format.ellipsis(data.storage_location, 15)
                                                        });


                                                        return data;

                                                    },
                                                    cls: 'my-dataview-cls',
                                                    itemId: 'hamperDataview',
                                                    overflowY: 'auto',
                                                    itemSelector: 'div.thumb-wrap',
                                                    itemTpl: [
                                                        '<tpl for=".">',
                                                        '    <div style="float:left;padding:	10px 30px 30px 10px;  "class=thumb-wrap id="id">',
                                                        '        <div class=thumb><img src="../cobuy_images/icons/{icon}"  height="90" width="50"></div>',
                                                        '        <div>',
                                                        '        <h5> <b>{shortName} </b></br></h5>',
                                                        '        <h5><em>{price} </em></br></h5>',
                                                        '        <h5> <b>{shortDesc} </b></br></h5>',
                                                        '            ',
                                                        '        <!--<spam>{description} </spam> -->',
                                                        '        <!--  <span style=class=x-editable>{shortDesc}</span>-->',
                                                        '        <!--<span style="padding-right:5px">price/user/yr:</span><span style=class=x-editable>{price}</span>-->',
                                                        '        <!--<span style="padding-right:5px">visibility:</span><span style=class=x-editable>{visibility}</span>',
                                                        '        <!--<span style="padding-right:5px">location:</span><span style=class=x-editable>{location}</span>-->',
                                                        '        <!--<br>min subscription no.:<span style="padding-left:5px">{min_subs_no}</span></br>-->',
                                                        '        </div>',
                                                        '        ',
                                                        '    </tpl>',
                                                        '<div class=x-clear></div>'
                                                    ],
                                                    preserveScrollOnRefresh: true,
                                                    store: 'HamperHasProducts'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 3,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            margin: 5,
                                            title: 'Remove Product from Hamper ',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 5,
                                                            itemId: 'removeproductName',
                                                            fieldLabel: 'Product',
                                                            labelWidth: 70,
                                                            name: 'remove_product_name',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 2,
                                                            itemId: 'removeproductfromhamperBtn',
                                                            margin: '0 0 0 3',
                                                            iconCls: 'delete_1',
                                                            text: 'Remove'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 3,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            margin: 5,
                                            title: 'Select  hamper container',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'combobox',
                                                            flex: 5,
                                                            itemId: 'hampercontainerCombo',
                                                            fieldLabel: 'Container',
                                                            labelWidth: 70,
                                                            name: 'hamper_container',
                                                            allowBlank: false,
                                                            editable: false,
                                                            displayField: 'name',
                                                            store: 'AllHamperContainers',
                                                            valueField: 'id'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 2,
                                                            itemId: 'hampercontainerBtn',
                                                            margin: '0 0 0 3',
                                                            iconCls: 'preview',
                                                            text: 'view'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 3,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            flex: 1,
                                            margin: 3,
                                            title: 'Cost of Hamper',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    itemId: 'costofhamperBox',
                                                    fieldLabel: 'Hamper Cost (=N=)',
                                                    labelWidth: 120,
                                                    name: 'cost_of_hamper',
                                                    readOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'add_product_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'remove_product_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'hamper_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'total_cost_for_computation'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Close'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'displayhamperBtn',
                            iconCls: 'add',
                            text: 'Display on store'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});