/*
 * File: app/view/AddNewAccountNumberForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AddNewAccountNumberForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addnewaccountnumberform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.form.field.Hidden'
    ],

    height: 350,
    width: 650,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Account Number Information',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Bank Name',
                            labelWidth: 150,
                            name: 'bank_name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Account Number',
                            labelWidth: 150,
                            name: 'account_number'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Account Title',
                            labelWidth: 150,
                            name: 'account_name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Swift Code',
                            labelWidth: 150,
                            name: 'swift_code'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Sort Code',
                            labelWidth: 150,
                            name: 'sort_code'
                        },
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    layout: 'column',
                                    title: 'Account Type',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'type',
                                            boxLabel: 'Savings Account',
                                            inputValue: 'savings'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            margin: '0 0 0 20',
                                            name: 'type',
                                            boxLabel: 'Current Account',
                                            inputValue: 'current'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            margin: '0 0 0 20',
                                            name: 'type',
                                            boxLabel: 'Domicilary Account',
                                            checked: true,
                                            inputValue: 'domiciliary'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            margin: '0 0 0 20',
                                            name: 'type',
                                            boxLabel: 'Hybrid Account',
                                            inputValue: 'hybrd'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    layout: 'column',
                                    title: 'Default Account Number',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'default_bank',
                                            boxLabel: 'Make this the default account number on the platfom',
                                            inputValue: '1'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'addBtn',
                            iconCls: 'add',
                            text: 'Add Account'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});