/*
 * File: app/view/AddRemoveProductFromMiddlePageAdvertForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AddRemoveProductFromMiddlePageAdvertForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addremoveproductfrommiddlepageadvertform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.form.field.Hidden',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 350,
    width: 500,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 5,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Product Information',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Name',
                                    name: 'name',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Code',
                                    name: 'code',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Cumulative Quantity',
                                    labelWidth: 150,
                                    name: 'cumulative_quantity',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Remaining Quantity',
                                    labelWidth: 150,
                                    name: 'quantity',
                                    readOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'id'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'service_id'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'category_id'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'product_type_id'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'whats_product_per_item'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 5,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Middle Page Advert Placement',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: 5,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            itemId: 'addproductRadio',
                                            name: 'operation',
                                            boxLabel: 'Add  Product to Advert ',
                                            inputValue: 'add'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            flex: 1,
                                            itemId: 'removeproductRadio',
                                            name: 'operation',
                                            boxLabel: 'Remove Product from Advert',
                                            inputValue: 'remove'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'advertplacementBtn',
                            iconCls: 'edit',
                            text: 'Advert Placement'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});