/*
 * File: app/view/AssigningSpecificationsValuesToProductForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssigningSpecificationsValuesToProductForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.assigningspecificationsvaluestoproductform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 600,
    width: 800,
    autoScroll: true,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    title: 'Product type and Product',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'producttypeCombo',
                            fieldLabel: 'Product Type',
                            name: 'producttype',
                            allowBlank: false,
                            editable: false,
                            displayField: 'name',
                            store: 'ProductTypes',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'productCombo',
                            fieldLabel: 'Product',
                            name: 'product',
                            allowBlank: false,
                            editable: false,
                            displayField: 'name',
                            store: 'Products',
                            valueField: 'id'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 5,
                    autoScroll: true,
                    title: 'Product Unique Specification',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Released Date',
                            labelWidth: 300,
                            name: 'released_date[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Form Factor',
                            labelWidth: 300,
                            name: 'form_factor[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Dimension',
                            labelWidth: 300,
                            name: 'dimension[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Weight',
                            labelWidth: 300,
                            name: 'weight[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Battery Capacity',
                            labelWidth: 300,
                            name: 'battery_capacity[]'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Removeable Battery?',
                            labelWidth: 300,
                            name: 'battery_removeable[]',
                            editable: false,
                            displayField: 'choice',
                            store: 'BinaryChoice',
                            valueField: 'choice'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Colour',
                            labelWidth: 300,
                            name: 'colour[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Screen Size',
                            labelWidth: 300,
                            name: 'screen_size[]'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Touch Screen?',
                            labelWidth: 300,
                            name: 'touchscreen[]',
                            editable: false,
                            displayField: 'choice',
                            store: 'BinaryChoice',
                            valueField: 'choice'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution[]'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Resoution',
                            labelWidth: 300,
                            name: 'resolution'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_type_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'product_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'released_date_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'form_factor_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'dimension_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'weight_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'battery_capacity_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'removeable_battery_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'colour_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'screensize_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'touchscreen_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'resolution_specification_id'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'specifications[]'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            icon: '',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'saveBtn',
                            iconCls: 'save',
                            text: 'Save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});