/*
 * File: app/view/AssignSpecificationsToProducttypeForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssignSpecificationsToProducttypeForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.assignspecificationstoproducttypeform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 600,
    width: 600,
    bodyPadding: 10,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1.5,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Product Type',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Product Type',
                                    name: 'producttype',
                                    allowBlank: false,
                                    editable: false,
                                    displayField: 'name',
                                    store: 'ProductTypes',
                                    valueField: 'id'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 10,
                    itemId: 'specificationsSet',
                    padding: '0 0 0 10',
                    autoScroll: true,
                    title: 'Product Specifications'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'assignBtn',
                            iconCls: 'add',
                            text: 'Assign Specifications'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});