/*
 * File: app/view/AssigningSpecificationsValuesToProductGridpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssigningSpecificationsValuesToProductGridpanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.assigningspecificationsvaluestoproductgridpanel',

    requires: [
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View'
    ],

    height: 250,
    width: 400,
    store: 'ProductHasSpecifications',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 100,
                    dataIndex: 'string',
                    text: 'S/n'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'product_id',
                    text: 'Product'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'specification_id',
                    text: 'Specification'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'specification_value',
                    text: 'Specification Value'
                },
                {
                    xtype: 'datecolumn',
                    width: 200,
                    dataIndex: 'create_time',
                    text: 'Date Created'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'create_user_id',
                    text: 'Created By'
                }
            ]
        });

        me.callParent(arguments);
    }

});