/*
 * File: app/view/AssigningAccountToCountryWin.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssigningAccountToCountryWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.assigningaccounttocountrywin',

    requires: [
        'cobuy.view.AssigningAccountToCountryForm',
        'Ext.form.Panel'
    ],

    height: 290,
    width: 610,
    title: 'Edit Account Number',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'assigningaccounttocountryform'
                }
            ]
        });

        me.callParent(arguments);
    }

});