/*
 * File: app/view/AssignFeesToMembershipTypeForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssignFeesToMembershipTypeForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.assignfeestomembershiptypeform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 340,
    width: 600,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Assigning Fees To Membership Type',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Membership Type',
                            labelWidth: 150,
                            name: 'membertype',
                            editable: false,
                            displayField: 'name',
                            store: 'MembershipTypes',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'monthlyFeeCombo',
                            fieldLabel: 'Monthly Fee (=N=)',
                            labelWidth: 150,
                            name: 'fee',
                            editable: false,
                            displayField: 'amount_monthly',
                            store: 'MembershipFees',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'yearlyFeeCombo',
                            fieldLabel: 'Yearly Fee (=N=)',
                            labelWidth: 150,
                            name: 'yearly_fee',
                            readOnly: true,
                            editable: false,
                            displayField: 'amount',
                            store: 'MembershipFees',
                            valueField: 'id'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'fee_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'yearly_fee_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'membership_type_id',
                            value: 0
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: 'Status',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'status',
                                    boxLabel: 'Not Active',
                                    checked: true,
                                    inputValue: 'inactive'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'status',
                                    boxLabel: 'Active',
                                    inputValue: 'active'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'assignBtn',
                            iconCls: 'add',
                            text: 'Assign'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});