/*
 * File: app/view/AssignMembershipSubscriptionToFeesGridpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.AssignMembershipSubscriptionToFeesGridpanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.assignmembershipsubscriptiontofeesgridpanel',

    requires: [
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View'
    ],

    height: 250,
    width: 400,
    store: 'MembershiptypeHasFees',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                    dataIndex: 'string',
                    text: 'S/n'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var type = Ext.getStore('MembershipTypes');
                        var membertype = type.findRecord('id', value);
                        return membertype!== null ? membertype.get('name'): value;
                    },
                    width: 300,
                    dataIndex: 'membership_type_id',
                    text: 'Membership Type'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var fee = Ext.getStore('MembershipFees');
                        var MembershipFees = fee.findRecord('id', value);
                        return MembershipFees!== null ? MembershipFees.get('amount_monthly'): value;
                    },
                    width: 300,
                    dataIndex: 'fee_id',
                    text: 'Monthly Fee'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var fee = Ext.getStore('MembershipFees');
                        var MembershipFees = fee.findRecord('id', value);
                        return MembershipFees!== null ? MembershipFees.get('amount'): value;
                    },
                    width: 300,
                    dataIndex: 'yearly_fee_id',
                    text: 'Yearly Fee'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'status',
                    text: 'Status'
                },
                {
                    xtype: 'datecolumn',
                    width: 300,
                    dataIndex: 'create_time',
                    text: 'Create Time'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var userStore = Ext.getStore('AllMembers');
                        var user = userStore.findRecord('id', value);
                        if(user.get('middlename') === null || user.get('middlename') === undefined){
                            var name = user.get('firstname') + " " + user.get('lastname');
                        }else{
                            var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                        }

                        return user!== null ? name: value;
                    },
                    width: 300,
                    dataIndex: 'create_user_id',
                    text: 'Created By'
                },
                {
                    xtype: 'datecolumn',
                    width: 300,
                    dataIndex: 'update_time',
                    text: 'Date Updated'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var userStore = Ext.getStore('AllMembers');
                        var user = userStore.findRecord('id', value);
                        if(user.get('middlename') === null || user.get('middlename') === undefined){
                            var name = user.get('firstname') + " " + user.get('lastname');
                        }else{
                            var name = user.get('firstname') + " " + user.get('middlename') + " " + user.get('lastname');
                        }

                        return user!== null ? name: value;
                    },
                    width: 300,
                    dataIndex: 'update_user_id',
                    text: 'Updated By'
                }
            ]
        });

        me.callParent(arguments);
    }

});