/*
 * File: app/view/BankAccountsAssignedToACountryMainpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.BankAccountsAssignedToACountryMainpanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bankaccountsassignedtoacountrymainpanel',

    requires: [
        'cobuy.view.ListAllBankAccountsForCountryGrid',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.panel.Tool',
        'Ext.grid.Panel'
    ],

    height: 400,
    margin: '0 0 0 20',
    width: 600,
    layout: 'fit',
    title: 'Bank Accounts assigned To This Country',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'editBtn',
                            iconCls: 'edit',
                            text: 'Edit Country\'s Bank Account Info'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'approveBtn',
                            iconCls: 'approve_account',
                            text: 'Approve/Disapprove Bank Account for country'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'activateBtn',
                            iconCls: 'activate_account',
                            text: 'Activate/Deactivate Country Bank Account'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'deleteBtn',
                            iconCls: 'delete_1',
                            text: 'Remove Account from Country'
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        var panel = tool.up('bankaccountsassignedtoacountrymainpanel');

                        panel.hide();
                    }
                }
            ],
            items: [
                {
                    xtype: 'listallbankaccountsforcountrygrid'
                }
            ]
        });

        me.callParent(arguments);
    }

});