/*
 * File: app/view/ChangeTheQuantityOfHamperContentWin.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.ChangeTheQuantityOfHamperContentWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.changethequantityofhampercontentwin',

    requires: [
        'cobuy.view.ChangeTheQuantityOfHamperContentForm',
        'Ext.form.Panel'
    ],

    height: 250,
    width: 500,
    layout: 'fit',
    title: 'Change quantity of product in a hamper',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'changethequantityofhampercontentform'
                }
            ]
        });

        me.callParent(arguments);
    }

});