/*
 * File: app/view/GeneratingMembershipNumberForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.GeneratingMembershipNumberForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.generatingmembershipnumberform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.form.field.File',
        'Ext.toolbar.Separator'
    ],

    height: 650,
    width: 1000,
    bodyPadding: 10,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 10',
                    title: 'Membership Subscription',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1.5,
                            title: 'Login & Membership Information',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'User Name',
                                    labelWidth: 130,
                                    name: 'username',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Email',
                                    labelWidth: 130,
                                    name: 'email',
                                    readOnly: true,
                                    allowBlank: false,
                                    vtype: 'email'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    disabled: true,
                                    fieldLabel: 'Membership Type',
                                    labelWidth: 130,
                                    name: 'membership_type',
                                    readOnly: true,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    disabled: true,
                                    fieldLabel: 'Membership Number',
                                    labelWidth: 130,
                                    name: 'membership_number',
                                    readOnly: true,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    disabled: true,
                                    fieldLabel: 'Renewal Due Date',
                                    labelWidth: 130,
                                    name: 'renewal_due_date',
                                    readOnly: true,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    disabled: true,
                                    fieldLabel: 'Membership Status',
                                    labelWidth: 130,
                                    name: 'membership_status',
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'hiddenfield',
                                    anchor: '100%',
                                    fieldLabel: 'Label',
                                    name: 'id'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 2.7,
                            title: 'User Info',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'First Name',
                                    labelWidth: 130,
                                    name: 'firstname',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Middle Name',
                                    labelWidth: 130,
                                    name: 'middlename',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Last Name',
                                    labelWidth: 130,
                                    name: 'lastname',
                                    readOnly: true
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Gender',
                                    labelWidth: 130,
                                    name: 'gender',
                                    editable: false,
                                    displayField: 'gender',
                                    store: 'Gender',
                                    valueField: 'gender'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address1 ',
                                    labelWidth: 130,
                                    name: 'address1'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address2',
                                    labelWidth: 130,
                                    name: 'address2'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Country',
                                    labelWidth: 130,
                                    name: 'country',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Countries',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'State',
                                    labelWidth: 130,
                                    name: 'state',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'States',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'City',
                                    labelWidth: 130,
                                    name: 'city',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Cities',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    fieldLabel: 'Date of Birth',
                                    labelWidth: 130,
                                    name: 'dateofbirth',
                                    format: 'd/m/Y',
                                    submitFormat: 'm/d/Y'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Religion',
                                    labelWidth: 130,
                                    name: 'religion',
                                    editable: false,
                                    displayField: 'religion',
                                    store: 'Religion',
                                    valueField: 'religion'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Marital Status',
                                    labelWidth: 130,
                                    name: 'maritalstatus',
                                    editable: false,
                                    displayField: 'maritalstatus',
                                    store: 'MaritalStatus',
                                    valueField: 'maritalstatus'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 1,
                    margin: '0 0 0 10',
                    title: 'Additional Membership Subscription Information',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 0.9,
                            title: 'Membership Category Information & Contact Numbers',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Membership Category',
                                    labelWidth: 150,
                                    name: 'category',
                                    editable: false,
                                    displayField: 'category',
                                    store: 'MembershipCategory',
                                    valueField: 'category'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Landline',
                                    labelWidth: 150,
                                    name: 'landline'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Mobile Number',
                                    labelWidth: 150,
                                    name: 'mobile_line'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1.4,
                            title: 'Permenant Delivery Information',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 1',
                                    labelWidth: 150,
                                    name: 'delivery_address1'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 2',
                                    labelWidth: 150,
                                    name: 'delivery_address2'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Country',
                                    labelWidth: 150,
                                    name: 'delivery_country',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Countries',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'State',
                                    labelWidth: 150,
                                    name: 'delivery_state',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'States',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'City',
                                    labelWidth: 150,
                                    name: 'delivery_city',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Cities',
                                    valueField: 'id'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 2,
                            title: 'Additional Information for Corporate Memberships',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Name of Organization',
                                    labelWidth: 150,
                                    name: 'name_of_organization'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Unique Registration No',
                                    labelWidth: 150,
                                    name: 'unique_registration_number'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Business Category',
                                    labelWidth: 150,
                                    name: 'business_category',
                                    editable: false,
                                    displayField: 'business_category',
                                    store: 'BusinessCategory',
                                    valueField: 'business_category'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 1',
                                    labelWidth: 150,
                                    name: 'corporate_address1'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 2',
                                    labelWidth: 150,
                                    name: 'corporate_address2'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Country',
                                    labelWidth: 150,
                                    name: 'corporate_country',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Countries',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'State',
                                    labelWidth: 150,
                                    name: 'corporate_state',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'States',
                                    valueField: 'id'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'City',
                                    labelWidth: 150,
                                    name: 'corporate_city',
                                    editable: false,
                                    displayField: 'name',
                                    store: 'Cities',
                                    valueField: 'id'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    flex: 0.5,
                    margin: '0 0 0 10',
                    title: 'Member Picture & Password Change',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'toolbar',
                                    items: [
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'changepasswordBtn',
                                            iconCls: 'key',
                                            text: 'Change Password'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'fieldset',
                            flex: 2.7,
                            title: 'Member Picture',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 5,
                                    layout: 'fit',
                                    title: 'Existing Picture',
                                    items: [
                                        {
                                            xtype: 'image',
                                            itemId: 'memberPicture'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'filefield',
                                    flex: 1.5,
                                    margin: '3 0 0 0',
                                    fieldLabel: 'Change Picture (.png or jpg)',
                                    name: 'picture',
                                    buttonOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'city_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'state_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'country_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'delivery_city_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'delivery_state_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'delivery_country_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'corporate_city_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'corporate_state_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'corporate_country_id'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'role'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'status'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'usertype'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'membership_type_id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'generateBtn',
                            iconCls: 'add',
                            text: 'Generating Membership Number'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});