/*
 * File: app/view/HamperContainerDetailsForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.HamperContainerDetailsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.hampercontainerdetailsform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.Display',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    height: 350,
    width: 500,
    bodyPadding: 10,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1.5,
                    margin: 10,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            title: 'Hamper Container Details',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Name',
                                    name: 'name'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Amount(=N=)',
                                    labelWidth: 200,
                                    name: 'amount',
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Service Charge (in %)',
                                    labelWidth: 200,
                                    name: 'service_charge_in_percentages',
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Minimum Service Charge (=N=)',
                                    labelWidth: 200,
                                    name: 'minimum_service_charge',
                                    minValue: 0
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    fieldLabel: 'Weight (kg)',
                                    labelWidth: 200,
                                    name: 'weight',
                                    minValue: 0
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Code',
                                    name: 'code'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 10,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            layout: 'fit',
                            title: 'Description',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    name: 'description'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Close'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});