/*
 * File: app/view/LanguageGridpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.LanguageGridpanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.languagegridpanel',

    requires: [
        'Ext.grid.RowNumberer',
        'Ext.grid.View'
    ],

    height: 250,
    width: 400,
    store: 'Languages',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 50,
                    dataIndex: 'string',
                    text: 'S/n'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'name',
                    text: 'Language'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'create_time',
                    text: 'Created By'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'create_user_id',
                    text: 'Created By'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'update_time',
                    text: 'Date Updated'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'update_user_id',
                    text: 'Updated By'
                }
            ]
        });

        me.callParent(arguments);
    }

});