/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill'
    ],

    height: 280,
    width: 470,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    margin: '10 0 0 0',
                    title: 'Login Credentials',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '10 0 0 0 ',
                            fieldLabel: 'Username',
                            name: 'username'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            margin: '20 0 0 0',
                            fieldLabel: 'Password',
                            name: 'password',
                            inputType: 'password'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelloginBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            itemId: 'loginBtn',
                            iconCls: 'user',
                            text: 'Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});