/*
 * File: app/view/MembershipSubscriptionMainpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.MembershipSubscriptionMainpanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.membershipsubscriptionmainpanel',

    requires: [
        'cobuy.view.MembershipSubscriptionGridpanel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel'
    ],

    height: 250,
    width: 400,
    layout: 'fit',
    title: 'Membership Subscription Management',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'addBtn',
                            iconCls: 'add',
                            text: 'Add New Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'editBtn',
                            iconCls: 'edit',
                            text: 'Edit Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'activateBtn',
                            iconCls: 'activation',
                            text: 'Activate Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'deactivateBtn',
                            iconCls: 'deactivation',
                            text: 'Deactivate Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'suspendBtn',
                            iconCls: 'unlink',
                            text: 'Suspend Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'extendBtn',
                            iconCls: 'connection',
                            text: 'Extend Subscription'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'renewBtn',
                            iconCls: 'renewals',
                            text: 'Renew Subscription'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'membershipsubscriptiongridpanel'
                }
            ]
        });

        me.callParent(arguments);
    }

});