/*
 * File: app/view/ProductMainpanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.ProductMainpanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.productmainpanel',

    requires: [
        'cobuy.view.ProductGridpanel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.grid.Panel'
    ],

    height: 250,
    width: 400,
    layout: 'fit',
    title: 'Product Management',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'addBtn',
                            iconCls: 'add',
                            text: 'Add New Product'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'editBtn',
                            iconCls: 'edit',
                            text: 'Edit Product'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'modifyQuantityBtn',
                            iconCls: 'edit_2',
                            text: 'Modify Product Quantity'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'addtomiddleadvertBtn',
                            iconCls: 'add',
                            text: 'Add/Remove Product from Middle Page Advert'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'deleteBtn',
                            iconCls: 'delete',
                            text: 'Delete Product'
                        },
                        {
                            xtype: 'tbseparator',
                            hidden: true
                        },
                        {
                            xtype: 'button',
                            itemId: 'addvariationBtn',
                            iconCls: 'add',
                            text: 'Add Variation'
                        },
                        {
                            xtype: 'tbseparator',
                            hidden: true
                        },
                        {
                            xtype: 'button',
                            itemId: 'makevariationBtn',
                            iconCls: 'add',
                            text: 'Make Variation'
                        },
                        {
                            xtype: 'tbseparator',
                            hidden: true
                        },
                        {
                            xtype: 'button',
                            itemId: 'releasevariationBtn',
                            iconCls: 'delete',
                            text: 'Release Variation'
                        },
                        {
                            xtype: 'tbseparator',
                            hidden: true
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'hamperBtn',
                            iconCls: 'delete',
                            text: 'Add/Remove Products from Hamper'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'zeroriseBtn',
                            iconCls: '',
                            text: 'Zerorise Product/Pack Prices'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'productgridpanel'
                }
            ]
        });

        me.callParent(arguments);
    }

});