/*
 * File: app/view/ProductsInCartView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.ProductsInCartView', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    height: 250,
    width: 400,
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'dataview',
                    prepareData: function(data, recordIndex, record) {
                        /**
                        //get the exchange rate form from the store mainpanel

                        var form = Ext.getCmp('storewin').down('#rateform');

                        var rate = form.down('hiddenfield[name=rate]').getValue();

                        var currency_code = form.down('hiddenfield[name=code]').getValue();

                        var converted_value = rate* data.price;
                        Ext.apply(data, {
                            //shortDesc: Ext.util.Format.ellipsis(data.description, 20),
                            shortName: Ext.util.Format.ellipsis(data.name, 30),
                            price: Ext.util.Format.currency(converted_value,currency_code,2),
                            min_subs_no: Ext.util.Format.number(data.min_subscription_required, '0,000,000'),
                            visibility: Ext.util.Format.ellipsis(data.visibility, 15),
                            location: Ext.util.Format.ellipsis(data.storage_location, 15)
                        });


                        return data;

                        **/
                    },
                    itemSelector: 'div.thumb-wrap',
                    itemTpl: [
                        '<tpl for=".">',
                        '    <div style="float:left;padding:30px 30px 30px 15px;  "class=thumb-wrap id="id">',
                        '        <div class=thumb><img src="../cobuy_images/icons/{icon}" ></div>',
                        '        <div>',
                        '           <b>{shortName} </b></br>',
                        '            ',
                        '        <!--<spam>{description} </spam> -->',
                        '        <!--  <span style=class=x-editable>{shortDesc}</span>-->',
                        '        <!--<span style="padding-right:5px">price/user/yr:</span><span style=class=x-editable>{price}</span>-->',
                        '       <!-- <span style="padding-right:5px">visibility:</span><span style=class=x-editable>{visibility}</span>',
                        '        <!--<span style="padding-right:5px">location:</span><span style=class=x-editable>{location}</span>-->',
                        '        <!--<br>min subscription no.:<span style="padding-left:5px">{min_subs_no}</span></br>-->',
                        '        </div>',
                        '        ',
                        '    </tpl>',
                        '<div class=x-clear></div>'
                    ],
                    store: 'ProductsInCart'
                }
            ]
        });

        me.callParent(arguments);
    }

});