/*
 * File: app/view/RolesMain.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.RolesMain', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.rolesmain',

    requires: [
        'cobuy.view.RolesGrid',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill',
        'Ext.grid.Panel'
    ],

    height: 253,
    itemId: 'rolesmain',
    width: 600,
    layout: 'fit',
    title: 'Roles Management',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'createBtn',
                            iconCls: 'add',
                            text: 'Create New Role'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'editBtn',
                            iconCls: 'edit',
                            text: 'Edit Role Info'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'assignBtn',
                            iconCls: 'key',
                            text: 'Role Assignment'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'deleteBtn',
                            iconCls: 'delete_1',
                            text: 'Delete'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'rolesgrid1'
                }
            ]
        });

        me.callParent(arguments);
    }

});