/*
 * File: app/view/SearchProductForHamperForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.SearchProductForHamperForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.searchproductforhamperform',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 60,
    margin: 3,
    bodyPadding: 10,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    flex: 3,
                    itemId: 'serviceCombo',
                    margin: '0 0 10 0',
                    name: 'service',
                    value: 'All Services',
                    editable: false,
                    anyMatch: true,
                    displayField: 'name',
                    store: 'Services',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    flex: 3,
                    itemId: 'categoryCombo',
                    margin: '0 0 10 0',
                    name: 'productcategory',
                    value: 'All Categories',
                    editable: false,
                    anyMatch: true,
                    displayField: 'name',
                    queryMode: 'local',
                    store: 'ProductCategoryForAService',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    flex: 3,
                    itemId: 'typeCombo',
                    margin: '0 0 10 0',
                    name: 'producttype',
                    value: 'All Types',
                    editable: false,
                    anyMatch: true,
                    displayField: 'name',
                    queryMode: 'local',
                    store: 'ProductTypesForACategory',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    flex: 5,
                    itemId: 'storeSearchCombo',
                    margin: '0 0 10 3',
                    name: 'searchstring'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    itemId: 'hampersearchBtn',
                    margin: '0 0 10 5',
                    iconCls: 'search'
                }
            ]
        });

        me.callParent(arguments);
    }

});