/*
 * File: app/view/TermsAndConditionsForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.TermsAndConditionsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.termsandconditionsform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 574,
    width: 600,
    bodyPadding: 10,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 10,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1.5,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Content Status',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Status',
                                            name: 'status',
                                            editable: false,
                                            displayField: 'status',
                                            store: 'WebsiteStatus',
                                            valueField: 'status'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 9,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    autoScroll: true,
                                    layout: 'fit',
                                    title: 'Membership Terms & Conditions',
                                    items: [
                                        {
                                            xtype: 'htmleditor',
                                            height: 150,
                                            margin: 5,
                                            name: 'membership_terms_and_conditions'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 10,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            autoScroll: true,
                            layout: 'fit',
                            title: 'Purchase Terms & Conditions',
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    height: 150,
                                    margin: 5,
                                    name: 'purchase_terms_and_conditions'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 10,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'fieldset',
                            autoScroll: true,
                            layout: 'fit',
                            title: 'Generic Terms & Conditions',
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    height: 150,
                                    margin: 5,
                                    name: 'generic_terms_and_conditions'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'saveBtn',
                            iconCls: 'save',
                            text: 'Save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});