/*
 * File: app/view/TheCountryForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.TheCountryForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.thecountryform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.HtmlEditor',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.form.field.File',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 350,
    width: 600,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Country Details',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Name',
                            labelWidth: 120,
                            name: 'name'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Country Code',
                            labelWidth: 120,
                            name: 'country_code'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Continent',
                            labelWidth: 120,
                            name: 'continent',
                            editable: false,
                            displayField: 'continent',
                            store: 'Continent',
                            valueField: 'continent'
                        },
                        {
                            xtype: 'htmleditor',
                            anchor: '100%',
                            fieldLabel: 'Description',
                            labelWidth: 120,
                            name: 'description'
                        },
                        {
                            xtype: 'checkboxfield',
                            anchor: '100%',
                            name: 'enable_vat_collection',
                            boxLabel: 'Enable VAT Collection',
                            inputValue: '1'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Default Vat Rate(%)',
                            labelWidth: 120,
                            name: 'country_default_vat_rate',
                            minValue: 0
                        },
                        {
                            xtype: 'filefield',
                            anchor: '100%',
                            fieldLabel: 'Flag',
                            name: 'flag',
                            buttonOnly: true
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id',
                            value: 0
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'addBtn',
                            iconCls: 'add',
                            text: 'Save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});