/*
 * File: app/view/TheFailedPaymentForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.TheFailedPaymentForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.thefailedpaymentform1',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.toolbar.Fill'
    ],

    height: 528,
    width: 700,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Payment Details',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'orderCombo',
                            fieldLabel: 'Order Number',
                            labelWidth: 180,
                            name: 'order_number',
                            readOnly: true,
                            editable: false,
                            displayField: 'order_number',
                            store: 'Orders',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Invoice Number',
                            labelWidth: 180,
                            name: 'invoice_number',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Status',
                            labelWidth: 180,
                            name: 'status',
                            readOnly: true,
                            editable: false,
                            displayField: 'status',
                            store: 'PaymentStatus',
                            valueField: 'status'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Mode',
                            labelWidth: 180,
                            name: 'payment_mode',
                            readOnly: true,
                            editable: false,
                            displayField: 'payment_mode',
                            store: 'PaymentModes'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'bankCombo',
                            fieldLabel: 'Bank Account',
                            labelWidth: 180,
                            name: 'bank_account',
                            readOnly: true,
                            editable: false,
                            displayField: 'account_number',
                            store: 'Bankers',
                            valueField: 'id'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Products Amount(=N=)',
                            labelWidth: 180,
                            name: 'gross_amount_for_display'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Delivery Charges(=N=)',
                            labelWidth: 180,
                            name: 'delivery_charges'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Discounted Amount(=N=)',
                            labelWidth: 180,
                            name: 'discounted_amount_for_display'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Expected Income(=N=)',
                            labelWidth: 180,
                            name: 'revenue_for_display'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Vat(=N=)',
                            labelWidth: 180,
                            name: 'vat_for_display'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            fieldLabel: 'Total Amount in Bank(=N=)',
                            labelWidth: 180,
                            name: 'amount_in_bank'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'order_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'bank_account_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'paid_by',
                            value: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'gross_amount',
                            value: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'net_amount',
                            value: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'revenue',
                            value: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'vat',
                            value: 0
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Reason for Payment Failure',
                            labelWidth: 180,
                            name: 'reason_for_failure',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Delivery Type',
                            labelWidth: 180,
                            name: 'delivery_type'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: 'Payment Date',
                            labelWidth: 180,
                            name: 'payment_date',
                            readOnly: true,
                            editable: false,
                            format: 'd/m/Y',
                            submitFormat: 'm/d/Y'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Paid By',
                            labelWidth: 180,
                            name: 'payee',
                            readOnly: true
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cancelBtn',
                            iconCls: 'cancel',
                            text: 'Cancel'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'okBtn',
                            iconCls: 'confirmation',
                            text: 'Ok'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});