/*
 * File: app/view/TheProductForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cobuy.view.TheProductForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.theproductform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.File'
    ],

    height: 620,
    width: 1000,
    layout: 'fit',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Product Details',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            title: 'General Information',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 2,
                                    title: 'Product Info',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Name',
                                            name: 'name',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'serviceCombo',
                                            fieldLabel: 'Service',
                                            name: 'service',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            store: 'Services',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'categoryCombo',
                                            fieldLabel: 'Category',
                                            name: 'category',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            queryMode: 'local',
                                            store: 'ProductCategoryForAService',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'typeCombo',
                                            fieldLabel: 'Type',
                                            name: 'product_type',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            queryMode: 'local',
                                            store: 'ProductTypesForACategory',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            itemId: 'natureOfProductCombo',
                                            fieldLabel: 'Classification',
                                            name: 'nature_of_product',
                                            value: 'General',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'classification',
                                            queryMode: 'local',
                                            store: 'ProductClassification',
                                            valueField: 'nature_of_product'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 2.7,
                                    title: 'Availability,Product Container, Consumption Preference & Store Display',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            margin: '10 0 0 0',
                                            title: 'Consumption Preferences',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    itemId: 'rentableCheckbox',
                                                    name: 'is_rentable',
                                                    boxLabel: 'This Product is Rentable',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    itemId: 'paasCheckbox',
                                                    name: 'is_paas',
                                                    boxLabel: 'This Product could be consumed as a Service (PaaS)',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    disabled: true,
                                                    itemId: 'faasCheckbox',
                                                    name: 'is_faas',
                                                    boxLabel: 'This Product is strictly for Farming as a Service (FaaS)',
                                                    inputValue: '1'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            margin: '10 0 0 0',
                                            title: 'Availability, Product Container & Store Display',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    itemId: 'displayproductCheckbox',
                                                    name: 'displayable_on_store',
                                                    boxLabel: 'Display this product on the store',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    name: 'is_available',
                                                    boxLabel: 'This Product is Available',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    itemId: 'hamperCheckbox',
                                                    name: 'is_a_hamper',
                                                    boxLabel: 'Product is a Container of other Products or a Hamper',
                                                    inputValue: '1'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'category_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'service_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'product_type_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'target',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'product_variation_id',
                            value: 0
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'is_a_variation',
                            value: 0
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            margin: '0 10 0 10',
                            title: 'Pricing & Additional Product Information',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 3,
                                    title: 'Pricing Information',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'maximumQuantityNumberfield',
                                            fieldLabel: 'Maximum Quantity of Product on Sale',
                                            labelWidth: 280,
                                            name: 'quantity',
                                            minValue: -1
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            fieldLabel: 'Minimum Number of product item(s) to buy',
                                            labelWidth: 280,
                                            name: 'minimum_number_of_product_to_buy',
                                            allowBlank: false,
                                            minValue: 1
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'What constitutes per item of this product',
                                            labelWidth: 280,
                                            name: 'whats_product_per_item',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'prevailingPrice',
                                            fieldLabel: 'Prevailing Retail Selling Price per Item(=N=)',
                                            labelWidth: 280,
                                            name: 'prevailing_retail_selling_price',
                                            value: 0,
                                            allowBlank: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            itemId: 'memberPrice',
                                            fieldLabel: 'Cobuy Member Price per item(=N=)',
                                            labelWidth: 280,
                                            name: 'per_portion_price',
                                            value: 0,
                                            allowBlank: false,
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Headline Member Price Validity Period',
                                            labelWidth: 280,
                                            name: 'price_validity_period'
                                        },
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            fieldLabel: 'Start Member Special Price On',
                                            labelWidth: 280,
                                            name: 'start_price_validity_period',
                                            editable: false,
                                            format: 'd/m/Y',
                                            submitFormat: 'm/d/Y'
                                        },
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            fieldLabel: 'End Member Special Price on',
                                            labelWidth: 280,
                                            name: 'end_price_validity_period',
                                            editable: false,
                                            format: 'd/m/Y',
                                            submitFormat: 'm/d/Y'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            itemId: 'isQuotableCheckbox',
                                            name: 'is_quotable',
                                            boxLabel: 'Ask buyer to request for a quote',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            itemId: 'isEscrowableCheckbox',
                                            name: 'is_escrowable',
                                            boxLabel: 'An Escrow(a trade assurance policy) could be implemented on this product',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            itemId: 'isFutureTradable',
                                            name: 'is_future_tradable',
                                            boxLabel: 'Payment Scheduling is permitted on this Product',
                                            inputValue: '1'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            itemId: 'isPayableOnDelivery',
                                            name: 'is_payment_permitted_on_delivery',
                                            boxLabel: 'Product is Payable on Delivery',
                                            inputValue: '1'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Inclusion of Video Content',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    anchor: '100%',
                                                    itemId: 'isVideoIncluded',
                                                    name: 'is_with_video',
                                                    boxLabel: 'Video Content is included',
                                                    inputValue: '1'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    anchor: '100%',
                                                    disabled: true,
                                                    itemId: 'videoForThisPurpose',
                                                    fieldLabel: 'Purpose of this video',
                                                    labelWidth: 150,
                                                    name: 'video_for',
                                                    editable: false,
                                                    displayField: 'video_for',
                                                    store: 'VideoPurpose',
                                                    valueField: 'video_for'
                                                },
                                                {
                                                    xtype: 'filefield',
                                                    anchor: '100%',
                                                    disabled: true,
                                                    itemId: 'videoFilename',
                                                    fieldLabel: 'Video File (.mp4)',
                                                    labelWidth: 150,
                                                    name: 'video_filename',
                                                    buttonOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});